### ISSUE TITLE
Error when submitting via AJAX

### ISSUE THREAD

**Issue by paulrudy** [aaronhipple/grav-plugin-mailchimp#25]
I'd really like AJAX form submission to work with your excellent plugin. But it doesn't.  Since it throws an error, I hope you don't mind that I'm submitting this as a new issue instead of the comments I posted on [this closed issue](https://github.com/aaronhipple/grav-plugin-mailchimp/issues/9).  I do hope it is an easy fix to get your plugin to work with AJAX.

Steps taken:

1. Download and install latest grav v 1.6.26
2. `bin/gpm install form mailchimp` 
3. Add a page '/user/pages/03.contact/form.md'

 '/user/pages/03.contact/form.md':

```yaml
---
title: Contact

form:
   name: ajax-test-form
   template: form-messages
   action: '/contact'
   refresh_prevention: true

   fields:
      name:
         label: Your Email
         type: email

   buttons:
      submit:
         type: submit
         value: Submit

   process:
      mailchimp:
        lists: []
      message: 'Thank you for your submission!'
---

<div id="form-result"></div>

<script>
$(document).ready(function(){

   var form = $('#ajax-test-form');
   form.submit(function(e) {
      // prevent form submission
      e.preventDefault();

      // submit the form via Ajax
      $.ajax({
         url: form.attr('action'),
         type: form.attr('method'),
         dataType: 'html',
         data: form.serialize(),
         success: function(result) {
            // Inject the result in the HTML
            $('#form-result').html(result);
         }
      });
   });
});
</script>
```

4. Submit form while recording network log in Chrome devtools.

Result: No form submission and no success message.  The browser console shows 

```
POST https://mysite.com/contact 500 (Internal Server Error)  jquery-2.x.min.js:4 
send @ jquery-2.x.min.js:4
ajax @ jquery-2.x.min.js:4
(anonymous) @ contact:287
dispatch @ jquery-2.x.min.js:3
r.handle @ jquery-2.x.min.js:3
```

I get this error under Network > Response:

`{"error":{"type":"Error","message":"Class 'AaronHipple\\Grav\\Plugin\\MailChimp\\ErrorLoggingMailChimp' not found","file":"\/<PATH TO MY GRAV INSTALL>\/user\/plugins\/mailchimp\/mailchimp.php","line":128}}`

I'd be grateful if the plugin can be made to work with AJAX.
