### ISSUE TITLE
Allow optional field mappings

### ISSUE THREAD

**Issue by paulrudy** [aaronhipple/grav-plugin-mailchimp#26]
In a form where there are optional fields that have field mappings defined, the plugin will not process if the optional fields have been left blank. Example frontmatter:

```yaml
form:
    name: subscribe
    fields:
        email:
            label: 'Email Address'
            placeholder: Email
            type: text
            validate:
                rule: email
                required: true
        first_name:
            label: 'First Name (optional)'
            placeholder: First
            type: text
            classes: name-field
            validate:
                required: false
        last_name:
            label: 'Last Name (optional)'
            placeholder: Last
            type: text
            classes: name-field
            validate:
                required: false
    buttons:
        submit:
            type: submit
            value: Submit
        reset:
            type: reset
            value: Reset
    process:
        mailchimp:
            lists:
                - 0123456789
            field_mappings:
                FNAME: first_name
                LNAME: last_name
```
It would be a useful addition to the plugin if it would account for optional form fields, and submit and map only those fields that have been filled.
