### ISSUE TITLE
Ajax support?

### ISSUE THREAD

**Issue by Sogl** [aaronhipple/grav-plugin-mailchimp#9]
Hello!

Can I use your plugin with AJAX like described here?
https://learn.getgrav.org/forms/forms/how-to-ajax-submission

Do you have an example?

**Comment by aaronhipple** [comment]
I expect you could, though I've not run it myself. The README's [usage example](https://github.com/aaronhipple/grav-plugin-mailchimp#usage) simply documents the addition of a process step that submits certain fields into Mailchimp, as configured. This can be run inside just about any other kind of configuration you'd want, provided your form can sensibly map data into a shape useful for Mailchimp.

The documentation you've linked provides [a simple form configuration](https://learn.getgrav.org/forms/forms/how-to-ajax-submission#creating-the-form) to which you would add a process step like so:

```yaml
form:
    name: ajax-test-form
    template: form-messages
    refresh_prevention: true

    fields:
        name:
            label: Your Name
            type: text

    buttons:
        submit:
            type: submit
            value: Submit

    process:
        - mailchimp:                        # Our new process step should
            lists: [a1b2c3d4e5f6]         # handle submissions regardless
            field_mappings:               # of the configuration of the
                mailchimpNameField: name  # remaining process steps.
        - message: 'Thank you for your submission!'
```

Any additional fields you need should be added, and of course a field with the name `email` is necessary -- [we'll pick it up and run with it from there](https://github.com/aaronhipple/grav-plugin-mailchimp/blob/23c436206b98052449763bac271c1e2185d9be3f/mailchimp.php#L144).

The remainder of the 'AJAX' part of the form is handled with [some very nicely generalized JavaScript](https://learn.getgrav.org/forms/forms/how-to-ajax-submission#the-page-content) that simply submits the form (no matter the configuration) and writes the resulting message into the messages area. It really shouldn't need to change to accommodate the Mailchimp process step -- only to accommodate your own needs.

If you do get a working example up and running, I'd happily accept a pull request to include it into the documentation!
